<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

add_action('genesis_before_sidebar_widget_area', 'ww_add_section');

function ww_add_section() {

  global $wp_query;
  $ww_id = $wp_query->post->ID;

  $votes = get_post_meta($ww_id, "votes", true);
  $votes = ($votes == "") ? 0 : $votes;

  echo '<section id="vote_counter_widget" class="widget"><div class="widget-wrap"><h4 class="widget-title widgettitle">Voting</h4><div>This post has <span id="vote_counter">' . $votes . ' </span> votes</div>';

  $nonce = wp_create_nonce("ww_user_vote_nonce");
  $link = admin_url('admin-ajax.php?action=ww_user_vote&post_id='.$ww_id.'&nonce='.$nonce);
  echo '<a class="user_vote button" data-nonce="' . $nonce . '" data-post_id="' . $ww_id . '" href="' . $link . '" style="color: #fff;"><i class="fas fa-trophy"></i> Vote for this article</a></div></section>';
}

genesis();
